### ISSUE TITLE
Bring back Tana-styled bullet blocks

### ISSUE THREAD

**Issue by krillin666** [henices/logseq-flow-nord#7]
Hi!

Thank you for picking up the Flow theme and continuing this great work.

One featured I used extensively with the original Flow theme was the Tana-styled bullet blocks, however it seems your port does not support this feature.

Would it be possible to support it ?

Thank you

**Comment by henices** [comment]
Hi,

I disabled Tana-styled bullet feature in Flow Nord Theme due to the poor performance while a page has a large number of blocks.

I'm not a Tana user, so I don't know what the extact meaning of Tana-styled bullet blocks. Could you please show me a screenshot with this feature.

BTW, the original code is still there, if this feature is quite useful ,  I'll consider bring it back.

**Comment by henices** [comment]
If you could add additional information, feel free to reopen this issue. Thanks a lot.
